package com.example.rh.enums;

public enum NotificationType {
    STAGE_CREATED,
    APPLICATION_RECEIVED,
    APPLICATION_CANCELED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    STAGE_ASSIGNED,
    EVALUATION_COMPLETED,
    OTHER
}
