package com.example.rh.enums;

public enum Permissions {
    CREATE_STAGE,
    APPLY_FOR_STAGE,
    ASSIGN_ENCADRANT,
    VIEW_CANDIDATES,
    SELECT_STAGIAIRES,
    REJECT_APPLICATION,
    ACCEPT_APPLICATION,
    UPDATE_STAGE,
    DELETE_STAGE,
    GET_STAGE,
    GET_ALL_STAGES,
    GET_STAGES_BY_STATE,
    UPDATE_STAGE_STATE,
    GET_MY_APPLICATIONS,
    My_STAGIARES

}
